#!/usr/bin/env bash

# This script was slightly adapted from
# https://github.com/jnsgruk/nixos-config/blob/675c71cbec13c9166b37595f800129bce74a27e3/scripts/install-with-disko

set -euo pipefail
TARGET_HOST="${1:-}"

cd /iso/config

if [[ "$(id -u)" -eq 0 ]]; then
  echo "ERROR! $(basename "${0}") should be run as a regular user"
  exit 1
fi

if [[ -z "$TARGET_HOST" ]]; then
    echo "ERROR! $(basename "${0}") requires a hostname as the first argument"
    exit 1
fi

if [[ ! -e "machines/${TARGET_HOST}/disko.nix" ]]; then
    echo "ERROR! $(basename "${0}") could not find the required machines/${TARGET_HOST}/disko.nix"
    exit 1
fi

if [[ ! -e "sops-secrets/key.txt" ]]; then
    echo "ERROR! $(basename "${0}") could not find the system wide sops key in /iso/config/sops-secrets/key.txt"
    exit 1
fi

if [[ ! -e "home-manager/sops-secrets/keys/dyson.txt" ]]; then
    echo "WARNING! $(basename "${0}") could not find the user-level sops key for dyson in /iso/config/home-manager/sops-secrets/keys/dyson.txt"

    read -p "Do you want to continue without this secret key? [y/N]" -n 1 -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

password_files="$(grep -Po '(?<=passwordFile = ")[^"]+(?=";)' "machines/${TARGET_HOST}/disko.nix" | uniq)"

while IFS= read -r password_file; do
	if [[ ! -f "$password_file" ]]; then
		echo "ERROR! ${TARGET_HOST} requires a LUKS password in ${password_file} but this file was not found"
		echo "Please write to this file with \`echo -n \"password\" > ${password_file}\` and try again"
		exit 1
	fi
done <<< "$password_files"

echo "WARNING! The disks in ${TARGET_HOST} are about to get wiped"
echo "         NixOS will be re-installed"
echo "         This is a destructive operation"
echo
read -p "Are you sure? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo DISKOCOMMAND --mode disko "machines/${TARGET_HOST}/disko.nix"

    # Rsync my nix-config to the target install
    sudo mkdir -p "/mnt/etc/nixos"
    sudo rsync -a --delete "/iso/config/" "/mnt/etc/nixos"

    sudo nixos-install --flake ".#${TARGET_HOST}"
else
	echo "Cancelling installation"
	exit 1
fi
