name: Build images

on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v27

      - uses: cachix/cachix-action@v14
        with:
          name: doctordalek1963
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the ISO
        run: nix build .#nixosConfigurations.iso.config.system.build.isoImage --print-build-logs

  build-raspi-sd:
    # I have no idea why this job fails in CI. It works completely fine when
    # I run it locally, but GitHub Actions doesn't like it, so I'm disabling
    # it for now.
    if: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3

      - uses: nixbuild/nix-quick-install-action@v27
        with:
          nix_conf: "extra-platforms = aarch64-linux"

      - uses: cachix/cachix-action@v14
        with:
          name: doctordalek1963
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the RasPi SD image
        run: nix build .#nixosConfigurations.Bert-NixOS.config.system.build.sdImage --print-build-logs
