name: Build images

on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@v17

      - name: Build the ISO
        run: nix build .#nixosConfigurations.iso.config.system.build.isoImage --print-build-logs --show-trace

  build-raspi-sd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'carve' # Keep docker for qemu

      - uses: docker/setup-qemu-action@v3

      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
            substituters = https://cache.nixos.org https://nix-community.cachix.org https://doctordalek1963.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= doctordalek1963.cachix.org-1:ide2OUuSBdJY4mSTyIanZaafJhcHNA5fFh6P633b8EI=

      - name: Build the RasPi SD image
        run: nix build .#nixosConfigurations.Bert-NixOS.config.system.build.sdImage --print-build-logs --show-trace
