name: Build images

on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main

      - uses: DeterminateSystems/nix-installer-action@v17

      - uses: cachix/cachix-action@v16
        with:
          name: doctordalek1963
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the ISO
        run: nix build .#nixosConfigurations.iso.config.system.build.isoImage --print-build-logs

  build-raspi-sd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: docker/setup-qemu-action@v3

      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: "extra-platforms = aarch64-linux"

      - uses: cachix/cachix-action@v16
        with:
          name: doctordalek1963
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the RasPi SD image
        run: nix build .#nixosConfigurations.Bert-NixOS.config.system.build.sdImage --print-build-logs
