name: Cache missing paths on Cachix

on: push

jobs:
  push-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'carve'

      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
            substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.lix.systems https://doctordalek1963.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.lix.systems:aBnZUw8zA7H35Cz2RyKFVs3H4PlGTLawyY5KRbvJR8o= doctordalek1963.cachix.org-1:ide2OUuSBdJY4mSTyIanZaafJhcHNA5fFh6P633b8EI=

      - uses: cachix/cachix-action@v16
        with:
          name: doctordalek1963
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          useDaemon: false

      - name: Push missing paths
        run: nix develop --command just cachix-push-all
