name: Check the flake

on: push

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'carve' # Keep docker for qemu

      - uses: docker/setup-qemu-action@v3

      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: "extra-platforms = aarch64-linux"

      - name: Check the NixOS flake
        run: nix flake check . --print-build-logs --keep-going --show-trace
