name: Check the flake

on: push

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: docker/setup-qemu-action@v3

      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: "extra-platforms = aarch64-linux"

      - uses: cachix/cachix-action@v16
        with:
          name: doctordalek1963
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check the NixOS flake
        run: nix flake check . --print-build-logs --keep-going
